### ISSUE TITLE
Odd build issue related to common.h

### ISSUE THREAD

**Issue by TRIA** [Fundacio-i2CAT/rinasense#20]
When attempting a native build on Linux 20.04, latest IDF, I got an odd compilation error in ARP826.h related to MACAddress_t, which is defined in the header file components/IPCP/include/common.h.  Note that common.h *is* included by ARP826.h, as "common.h", so it's a build problem, not a coding problem.  Error output attached below.

This could be that because the name "common.h" is used by multiple components of the IDF SDK, the wrong one is being picked up by CMake in some corner case of order of inclusion and computing dependencies (I'm building from command line, using standard processes: cmake in fresh build directory, then make all in rinasource.  It is odd that the build got as far as it did without hitting this before.  The safest thing to do would be to rename components/IPCP/include/common.h

Doing a verbose make all, and grepping for common.h, this shows up many times:

****      No need to remake target '/home/srb/esp/esp-idf/components/mbedtls/mbedtls/library/common.h'.

so CMake is definitely aware of and using multiple common.h files.

-----Here are the other files named by common.h in the SDK:
>
srb@sdr2:rinasense$ find $IDF_PATH -name common.h -print
/home/srb/esp/esp-idf/components/mbedtls/mbedtls/library/common.h
/home/srb/esp/esp-idf/components/mbedtls/mbedtls/programs/fuzz/common.h
/home/srb/esp/esp-idf/components/tinyusb/tinyusb/hw/bsp/fomu/include/hw/common.h
/home/srb/esp/esp-idf/components/wpa_supplicant/src/utils/common.h
/home/srb/esp/esp-idf/components/json/cJSON/tests/common.h
/home/srb/esp/esp-idf/components/bt/host/nimble/nimble/apps/blemesh_models_example_2/src/common.h
/home/srb/esp/esp-idf/components/openthread/openthread/third_party/mbedtls/repo/library/common.h
/home/srb/esp/esp-idf/components/openthread/openthread/third_party/mbedtls/repo/programs/fuzz/common.h
srb@sdr2:rinasense$   

----failing compile output:
>
[ 94%] Built target __idf_wifi_provisioning
[ 94%] Built target __idf_configSensor
[ 94%] Built target __idf_configRINA
[ 94%] Built target __idf_ARP826
[ 94%] Built target __idf_NetworkInterface
[ 94%] Built target __idf_BufferManagement
[ 94%] Built target __idf_ShimIPCP
[ 95%] Built target __idf_IPCP
[ 96%] Built target __idf_Enrollment
[ 96%] Built target __idf_FlowAllocator
[ 97%] Built target __idf_Ribd
[ 97%] Built target __idf_RINA_API
[ 97%] Built target __idf_Rmt
[ 97%] Built target __idf_EFCP
[ 98%] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj
... cut warnings about duplicate definition of offsetof... 
In file included from /home/srb/rinasense/components/IPCP/include/IPCP.h:10,
                 from /home/srb/rinasense/main/main.c:9:
/home/srb/rinasense/components/ARP826/include/ARP826.h:42:2: error: unknown type name 'MACAddress_t'
  MACAddress_t  xAddress;
  ^~~~~~~~~~~~
/home/srb/rinasense/components/ARP826/include/ARP826.h:48:2: error: unknown type name 'MACAddress_t'
  MACAddress_t xDestinationAddress; /**< Destination address  0 + 6 = 6  */
  ^~~~~~~~~~~~
/home/srb/rinasense/components/ARP826/include/ARP826.h:49:2: error: unknown type name 'MACAddress_t'
  MACAddress_t xSourceAddress;      /**< Source address       6 + 6 = 12 */
  ^~~~~~~~~~~~
.... cut more errors/warnings....
In file included from /home/srb/rinasense/main/main.c:9:
/home/srb/rinasense/components/IPCP/include/IPCP.h:128:47: warning: 'struct dtcpConfig_t' declared inside parameter list will not be visible outside of this definition or declaration
                                        struct dtcpConfig_t *        dtcp_config);
                                               ^~~~~~~~~~~~
make[2]: *** [esp-idf/main/CMakeFiles/__idf_main.dir/build.make:63: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:5022: esp-idf/main/CMakeFiles/__idf_main.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
srb@sdr2:~/rinasense$

**Comment by TRIA** [comment]
Three examples of this now show up in the latest dev branch, all are found in components/IPCP/include/common.h:
MACAddress_t
eFrameProcessingResult_t
seqNum_t

**Comment by TRIA** [comment]
Closed by latest commits.
